name: faker_app_flutter_firebase
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.6
  flutter_riverpod: ^2.4.10
  go_router: ^13.2.0
  equatable: 2.0.5
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.5
  firebase_ui_auth: ^1.13.0
  cloud_firestore: ^4.15.5
  faker: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1

flutter:
  uses-material-design: true
